// <auto-generated />
namespace OpenNos.DAL.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0-beta1-61231")]
    public sealed partial class Aphrodite88 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Aphrodite88));
        
        string IMigrationMetadata.Id
        {
            get { return "201808061821525_Aphrodite88"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
